function [SUBJ, YYYY, MM, DD, ARRAY, BLOCK] = quick_selector_gui(options)
%QUICK_SELECTOR_GUI   Blocking function to manually select key experiment parameters (for constructor).
%
% Syntax:
%   [SUBJ, YYYY, MM, DD, ARRAY, BLOCK] = io.quick_selector_gui('Name', value, ...);
%
% Inputs:
%   See elements of `arguments` block (or tab-complete)
%   
% Output:
%   [SUBJ, YYYY, MM, DD, ARRAY, BLOCK] - Typical arguments for loading TMSi
%                                           data collected using MATLAB 
%                                               2TMSi setup.
%
% See also: Contents, MetaDataHandler (2TMSi_... repo)

arguments
    options.Subject {mustBeTextScalar} = 'Max';
    options.Date (1,1) datetime = datetime('now','Format','uuuu-MM-dd''T''HH:mm:ss.SSS');
    options.Array = ["A", "B"];
    options.Block (1,1) {mustBeInteger} = 0;
    options.Name {mustBeTextScalar} = 'Set Subject Parameters';
    options.EnableDatePicker {mustBeMember(options.EnableDatePicker, {'on', 'off'})} = 'on';
    options.EnableSubjectPicker {mustBeMember(options.EnableSubjectPicker, {'on', 'off'})} = 'on';
    options.EnableArrayPicker {mustBeMember(options.EnableArrayPicker, {'on', 'off'})} = 'on';
    options.EnableBlockPicker {mustBeMember(options.EnableBlockPicker, {'on', 'off'})} = 'on';
end

fig = uifigure(...
    'Name', options.Name, ...
    'Color', 'w', ...
    'WindowStyle', 'alwaysontop', ...
    'Position', [240 420 580 225], ...
    'CloseRequestFcn', @handle_figure_close_cb);
SUBJ = options.Subject;
YYYY = year(options.Date);
MM = month(options.Date);
DD = day(options.Date);
ARRAY = options.Array;
BLOCK = options.Block;
d = uidatepicker(fig, 'Position', [210 125 200 50], ...
    'FontName', 'Tahoma', ...
    'FontSize', 15, ...
    'DisplayFormat', 'yyyy-MM-dd', ...
    'Enable', options.EnableDatePicker,...
    'Value', options.Date);
n = uidropdown(fig, 'Position', [50 125 100 50], ...
    'FontName', 'Tahoma', ...
    'FontSize', 15, ...
    'Editable', 'on', ...
    'Items', {'Mats', 'Chaitanya', 'Pulkit', 'Doug', 'Jonathan', 'Max', 'Jiaming', 'Forrest', 'Screamy', 'Slinky', 'Rascal', 'Ollie', 'Rupert', 'Spencer', 'Frank', 'Beanz'}, ...
    'Enable', options.EnableSubjectPicker,...
    'Value', options.Subject);
uilabel(fig, 'Position', [160 50 50 50], ...
    'FontName', 'Tahoma', ...
    'FontSize', 15, ...
    'VerticalAlignment', 'center', ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', ...
    'Text', 'SAGA:');
a = uidropdown(fig, 'Position', [210 50 200 50], ...
    'FontName', 'Tahoma', ...
    'FontSize', 15, ...
    'Editable', 'off', ...
    'Items', {'A', 'B', 'Both'}, ...
    'ItemsData', {"A", "B", ["A", "B"]}, ...
    'Enable', options.EnableArrayPicker,...
    'Value', options.Array);
b = uispinner(fig, ...
    'Position', [50 50 100 50], ...
    'FontName', 'Tahoma', ...
    'FontSize', 15, ...
    'RoundFractionalValues', 'on', ...
    'Enable', options.EnableBlockPicker,...
    'Value', options.Block);
uibutton(fig, ...
    'Position', [460 87 75 50], ...
    'FontName', 'Tahoma', ...
    'FontWeight', 'bold', ...
    'FontSize', 16, ...
    'Text', 'Submit', ...
    'ButtonPushedFcn', @(~, ~)close(fig));
waitfor(fig);

    function handle_figure_close_cb(src, ~)
        try
            SUBJ = n.Value;
            YYYY = year(d.Value);
            MM = month(d.Value);
            DD = day(d.Value);
            BLOCK = b.Value;
            ARRAY = a.Value;
            delete(src);
        catch me
            warning(me.message);
            delete(src);
        end
    end

end